# -*- coding: utf-8 -*-
"""
/***************************************************************************
 to_wkt
                                 A QGIS plugin
 This plugin provides the WKT geometry from the active layer selected feature 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-03
        copyright            : (C) 2024 by David Castellvell Buchaca
        email                : dcastellvell@gencat.cat
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load to_wkt class from file to_wkt.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WKT_maker import to_wkt
    return to_wkt(iface)
